# Generated by Django 4.2 on 2024-07-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestInterface', '0002_testinterfacecasemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testinterface',
            options={'verbose_name_plural': '接口表'},
        ),
        migrations.AlterModelOptions(
            name='testinterfacecasemodel',
            options={'verbose_name_plural': '测试用例表'},
        ),
    ]
