# Generated by Django 4.2 on 2024-07-14 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='测试文件', upload_to='', verbose_name='测试文件')),
                ('info', models.JSONField(default=list, help_text='测试文件数据信息', verbose_name='测试文件数据信息')),
            ],
            options={
                'verbose_name_plural': '测试文件表',
                'db_table': 'TestFile',
            },
        ),
        migrations.CreateModel(
            name='TestProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名字', max_length=50, verbose_name='项目名字')),
                ('leader', models.CharField(help_text='测试人名字', max_length=20, verbose_name='测试人名字')),
                ('created_time', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '测试项目表',
                'db_table': 'Testproject',
            },
        ),
        migrations.CreateModel(
            name='TestEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_variable', models.JSONField(blank=True, default=dict, help_text='全局变量', null=True, verbose_name='全局变量')),
                ('debug_global_variable', models.JSONField(blank=True, default=dict, help_text='debug模式全局变量', null=True, verbose_name='debug模式全局变量')),
                ('db', models.JSONField(default=dict, help_text='数据库配置', null=True, verbose_name='数据库配置')),
                ('host', models.CharField(blank=True, help_text='全局域名配置', max_length=200, null=True, verbose_name='全局域名配置')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='全局请求头', null=True, verbose_name='全局请求头')),
                ('global_func', models.TextField(blank=True, help_text='全局自定义函数', null=True, verbose_name='全局自定义函数')),
                ('name', models.CharField(default=list, help_text='测试环境名字', max_length=50, verbose_name='测试环境名字')),
                ('project', models.ForeignKey(help_text='项目关联外键', on_delete=django.db.models.deletion.CASCADE, to='Testproject.testproject', verbose_name='项目关联外键')),
            ],
            options={
                'verbose_name_plural': '测试环境表',
                'db_table': 'TestEnv',
            },
        ),
    ]
